'use strict';

const path = require('path');

function generateCode(projectData) {
 const { token = 'YOUR_BOT_TOKEN', name = 'Bot', prefix: rawPrefix = '!' } = projectData || {};
 const prefix = String(rawPrefix - '!').trim() || '!';
 const pluginRoot = path.resolve(__dirname, '..', 'plugins');
 const safeProject = { ...(projectData || {}), token: token || 'YOUR_BOT_TOKEN', prefix };

 return `// Generated by Kiodium - ${String(name || 'Bot').replace(/\r?\n/g, ' ')}
// Generated: ${new Date().toISOString()}
// Run with: npm install discord.js && node bot.js

const fs = require("fs");
const path = require("path");
const { Client, GatewayIntentBits, Partials } = require("discord.js");

if (typeof globalThis.File === "undefined") {
 try {
 const { File, Blob } = require("node:buffer");
 if (typeof globalThis.Blob === "undefined" && Blob) globalThis.Blob = Blob;
 if (File) globalThis.File = File;
 } catch {
 globalThis.File = class File {
 constructor(parts, fileName, options = {}) {
 this.parts = parts;
 this.name = String(fileName || "");
 this.type = options.type || "";
 this.lastModified = options.lastModified || Date.now();
 }
 };
 }
}

const PROJECT = ${JSON.stringify(safeProject, null, 2)};
const PLUGIN_ROOT = ${JSON.stringify(pluginRoot)};

const NODE_EVENT_DEFAULT = {
 event_channel: "channelCreate",
 event_client: "ready",
 event_emoji: "emojiCreate",
 event_guild: "guildCreate",
 event_member: "guildMemberAdd",
 event_role: "roleCreate",
};

const DISCORD_EVENT_TO_NODE = {
 channelCreate: "event_channel",
 channelDelete: "event_channel",
 channelUpdate: "event_channel",
 channelPinsUpdate: "event_channel",
 ready: "event_client",
 warn: "event_client",
 emojiCreate: "event_emoji",
 emojiDelete: "event_emoji",
 emojiUpdate: "event_emoji",
 guildCreate: "event_guild",
 guildDelete: "event_guild",
 guildUpdate: "event_guild",
 guildAvailable: "event_guild",
 guildMemberAdd: "event_member",
 guildMemberRemove: "event_member",
 guildMemberUpdate: "event_member",
 roleCreate: "event_role",
 roleDelete: "event_role",
 roleUpdate: "event_role",
};

function walkPluginDirs(root, out = []) {
 if (!fs.existsSync(root)) return out;
 for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
 const full = path.join(root, entry.name);
 if (!entry.isDirectory()) continue;
 if (fs.existsSync(path.join(full, "index.js"))) out.push(full);
 walkPluginDirs(full, out);
 }
 return out;
}

function loadPluginNodes(root) {
 const registry = {};
 for (const dir of walkPluginDirs(root)) {
 try {
 const mod = require(path.join(dir, "index.js"));
 const plugin = mod && mod.default ? mod.default : mod;
 for (const [type, definition] of Object.entries(plugin.nodes || {})) registry[type] = definition;
 } catch (err) {
 console.warn("[plugin-load]", dir, err.message);
 }
 }
 return registry;
}

function getOutputNodes(nodeId, nodes, edges, handleId = null) {
 return edges
 .filter((edge) => edge.source === nodeId && (handleId == null || edge.sourceHandle === handleId))
 .map((edge) => nodes.find((node) => node.id === edge.target))
 .filter(Boolean);
}

function template(text, vars) {
 return String(text || "").replace(/\\{([A-Za-z_][A-Za-z0-9_]*)\\}/g, (match, key) => (
 vars[key] === undefined || vars[key] === null ? match : String(vars[key])
 ));
}

function buildVars(message, prefix, command = "", rawArgs = "", extra = {}) {
 const parts = rawArgs ? rawArgs.split(/\\s+/).filter(Boolean) : [];
 return {
 user: message?.author?.username || "",
 username: message?.author?.username || "",
 tag: message?.author?.tag || "",
 id: message?.author?.id || "",
 userId: message?.author?.id || "",
 user_id: message?.author?.id || "",
 mention: message?.author?.id ? \`<@\${message.author.id}>\` : "",
 server: message?.guild?.name || "",
 guild: message?.guild?.name || "",
 serverId: message?.guild?.id || "",
 server_id: message?.guild?.id || "",
 channel: message?.channel?.name || "",
 channelId: message?.channel?.id || "",
 channel_id: message?.channel?.id || "",
 channelMention: message?.channel?.id ? \`<#\${message.channel.id}>\` : "",
 memberCount: String(message?.guild?.memberCount ?? ""),
 member_count: String(message?.guild?.memberCount ?? ""),
 prefix,
 command,
 args: rawArgs,
 arg0: parts[0] || "",
 arg1: parts[1] || "",
 arg2: parts[2] || "",
 message: message?.content || "",
 date: new Date().toISOString().slice(0, 10),
 time: new Date().toTimeString().slice(0, 8),
 ...extra,
 };
}

function buildEmbed(data, text) {
 const embed = {};
 if (text) embed.description = String(text).slice(0, 4096);
 if (data.embedTitle) embed.title = data.embedTitle;
 if (data.embedColor) {
 const color = parseInt(String(data.embedColor).replace("#", ""), 16);
 if (!Number.isNaN(color)) embed.color = color;
 }
 if (data.logoName || data.logoUrl) embed.author = { name: data.logoName || "\\u200b", icon_url: data.logoUrl || undefined };
 if (data.imageUrl) embed.image = { url: data.imageUrl };
 if (data.embedFooter) embed.footer = { text: data.embedFooter };
 return embed;
}

async function sendEmbed(message, data, text) {
 if (!message?.channel) return;
 if (data.embedEnabled === false) {
 if (text) await message.channel.send(String(text).slice(0, 2000));
 return;
 }
 await message.channel.send({ embeds: [buildEmbed(data, text)] });
}

const prefixStore = new Map();
function getPrefix(guildId = "global") {
 return prefixStore.get(guildId || "global") || prefixStore.get("global") || PROJECT.prefix || "!";
}
function setPrefix(nextPrefix, guildId = "global") {
 const clean = String(nextPrefix || "").trim() || PROJECT.prefix || "!";
 prefixStore.set(guildId || "global", clean);
 return clean;
}

async function runCustomCommandApi(node, message, prefix, fullCmd, rawArgs) {
 const data = node.data || {};
 const vars = buildVars(message, prefix, fullCmd, rawArgs);
 const method = String(data.apiMethod || "GET").toUpperCase();
 const headers = {};
 for (const line of template(data.apiHeaders || "", vars).split(/\\r?\\n/)) {
 const idx = line.indexOf(":");
 if (idx > 0) headers[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
 }
 const controller = new AbortController();
 const timer = setTimeout(() => controller.abort(), Math.max(1000, Number(data.apiTimeout || 15000)));
 try {
 const options = { method, headers, signal: controller.signal };
 if (!["GET", "HEAD"].includes(method)) options.body = template(data.apiBody || "", vars);
 const response = await fetch(template(data.apiUrl || "", vars), options);
 const contentType = response.headers.get("content-type") || "";
 const body = contentType.includes("application/json") ? await response.json() : await response.text();
 const result = typeof body === "string" ? body : JSON.stringify(body, null, 2);
 if (!response.ok) throw new Error(\`HTTP \${response.status} \${response.statusText}\`);
 const text = template(data.apiReply || data.reply || "{apiResult}", { ...vars, apiResult: result, apiJson: result, apiStatus: response.status, apiStatusText: response.statusText, apiOk: response.ok });
 await sendEmbed(message, data, text);
 } catch (err) {
 const text = template(data.apiErrorMessage || "API error: {apiError}", { ...vars, apiError: err.message, error: err.message });
 if (text) await message.channel.send(String(text).slice(0, 2000)).catch(() => {});
 } finally {
 clearTimeout(timer);
 }
}

function commandMatch(message, prefix, command) {
 const raw = String(command || "").trim();
 if (!raw) return null;
 const full = raw.startsWith(prefix) ? raw : prefix + raw;
 if (!message.content.toLowerCase().startsWith(full.toLowerCase())) return null;
 const rest = message.content.slice(full.length);
 if (rest && !/^\\s/.test(rest)) return null;
 return { full, rawArgs: rest.trim() };
}

async function executeNode(node, eventObj, eventType, prefix, helpers, visited = new Set(), depth = 0) {
 if (!node || visited.has(node.id) || depth > 50) return;
 visited.add(node.id);
 const nodes = PROJECT.nodes || [];
 const edges = PROJECT.edges || [];
 const def = PLUGINS[node.type];

 if (def && typeof def.execute === "function") {
 let cont = false;
 try {
 const ctx = { node, eventType, eventData: eventObj, message: eventType === "messageCreate" ? eventObj : null, prefix, ...helpers };
 const legacy = def.execute.length >= 2;
 cont = await Promise.resolve(legacy ? def.execute(node, eventObj, { ...helpers, prefix, eventType, eventData: eventObj }) : def.execute(ctx));
 } catch (err) {
 console.error("[node-error]", node.type, err);
 return;
 }
 if (cont) for (const next of getOutputNodes(node.id, nodes, edges)) await executeNode(next, eventObj, eventType, prefix, helpers, new Set(visited), depth + 1);
 return;
 }

 if (node.type === "custom_command" && eventType === "messageCreate") {
 const match = commandMatch(eventObj, prefix, node.data?.command);
 if (!match) return;
 if (node.data?.apiEnabled) await runCustomCommandApi(node, eventObj, prefix, match.full, match.rawArgs);
 else if (node.data?.reply) await sendEmbed(eventObj, node.data, template(node.data.reply, buildVars(eventObj, prefix, match.full, match.rawArgs)));
 for (const next of getOutputNodes(node.id, nodes, edges)) await executeNode(next, eventObj, eventType, prefix, helpers, new Set(visited), depth + 1);
 return;
 }

 if (node.type === "send_message" && eventObj?.channel) {
 await sendEmbed(eventObj, node.data || {}, template(node.data?.text || "", buildVars(eventObj, prefix)));
 for (const next of getOutputNodes(node.id, nodes, edges)) await executeNode(next, eventObj, eventType, prefix, helpers, new Set(visited), depth + 1);
 return;
 }

 if (node.type === "condition_branch" && eventObj?.content != null) {
 const value = String(node.data?.value || "");
 const condition = node.data?.condition || "starts_with";
 const ok = condition === "contains" ? eventObj.content.includes(value) : condition === "equals" ? eventObj.content === value : eventObj.content.startsWith(value);
 for (const next of getOutputNodes(node.id, nodes, edges, ok ? "true" : "false")) await executeNode(next, eventObj, eventType, prefix, helpers, new Set(visited), depth + 1);
 }
}

async function executeGraph(eventNode, eventObj, eventType, prefix, helpers) {
 for (const next of getOutputNodes(eventNode.id, PROJECT.nodes || [], PROJECT.edges || [])) {
 await executeNode(next, eventObj, eventType, prefix, helpers);
 }
}

function makeHelpers(prefix) {
 return {
 prefix,
 defaultPrefix: PROJECT.prefix || "!",
 getPrefix,
 setPrefix,
 buildEmbed,
 sendEmbed,
 allowedUsers: new Set(),
 allowedRoles: new Set(),
 cooldowns: new Map(),
 args: [],
 flow: {},
 };
}

const PLUGINS = loadPluginNodes(PLUGIN_ROOT);
const client = new Client({
 intents: [
 GatewayIntentBits.Guilds,
 GatewayIntentBits.GuildMessages,
 GatewayIntentBits.MessageContent,
 GatewayIntentBits.DirectMessages,
 GatewayIntentBits.GuildMembers,
 GatewayIntentBits.GuildEmojisAndStickers,
 GatewayIntentBits.GuildVoiceStates,
 GatewayIntentBits.GuildModeration,
 GatewayIntentBits.GuildWebhooks,
 GatewayIntentBits.GuildIntegrations,
 ].filter(Boolean),
 partials: [Partials.Channel],
});

client.once("ready", async () => {
 console.log(\`Logged in as \${client.user.tag}\`);
 for (const node of PROJECT.nodes || []) {
 const def = PLUGINS[node.type];
 if (def && typeof def.initProject === "function") {
 try {
 await def.initProject({ node, client, prefix: getPrefix("global"), ...makeHelpers(getPrefix("global")) });
 } catch (err) {
 console.error("[init-error]", node.type, err.message);
 }
 }
 }
});

client.on("messageCreate", async (message) => {
 if (message.author?.bot) return;
 const prefix = getPrefix(message.guild?.id);
 const helpers = makeHelpers(prefix);
 for (const eventNode of (PROJECT.nodes || []).filter((node) => node.type === "event_message")) {
 await executeGraph(eventNode, message, "messageCreate", prefix, helpers);
 }
});

for (const [eventName, nodeType] of Object.entries(DISCORD_EVENT_TO_NODE)) {
 client.on(eventName, async (...args) => {
 const eventData = eventName.endsWith("Update") ? (args[1] || args[0]) : args[0];
 const defaultEvent = NODE_EVENT_DEFAULT[nodeType];
 const matching = (PROJECT.nodes || []).filter((node) => node.type === nodeType && (node.data?.event || defaultEvent) === eventName);
 for (const eventNode of matching) {
 const prefix = getPrefix(eventData?.guild?.id);
 await executeGraph(eventNode, eventData, eventName, prefix, makeHelpers(prefix));
 }
 });
}

client.on("error", (err) => console.error("[discord-error]", err));
client.on("warn", (msg) => console.warn("[discord-warn]", msg));

client.login(PROJECT.token || process.env.DISCORD_TOKEN || "YOUR_BOT_TOKEN");
`;
}

module.exports = { generateCode };
