'use strict';

const DEMO_VALUES = {
  user: 'Akashsuu',
  username: 'Akashsuu',
  tag: 'Akashsuu#0000',
  user_tag: 'Akashsuu#0000',
  id: '123456789012345678',
  user_id: '123456789012345678',
  mention: '@Akashsuu',
  target: 'OwO#8456',
  targetName: 'OwO',
  target_name: 'OwO',
  targetId: '987654321098765432',
  target_id: '987654321098765432',
  targetMention: '@OwO',
  target_mention: '@OwO',
  afkMention: '@OwO',
  member: 'Akashsuu',
  memberMention: '@Akashsuu',
  prefix: '!',
  command: '!command',
  args: 'hello world',
  query: 'akashsuu',
  reason: 'No reason provided',
  error: 'No error',
  server: 'My Server',
  guild: 'My Server',
  guildId: '222222222222222222',
  guild_id: '222222222222222222',
  serverId: '222222222222222222',
  server_id: '222222222222222222',
  channel: 'general',
  channelName: 'general',
  channel_name: 'general',
  channelId: '333333333333333333',
  channel_id: '333333333333333333',
  channelMention: '#general',
  channel_mention: '#general',
  channelType: 'Text',
  category: 'Community',
  topic: 'General chat',
  nsfw: 'No',
  slowmode: '0s',
  position: '3',
  permissionsSummary: 'View Channel, Send Messages',
  createdAt: 'February 21, 2024',
  created_at: 'February 21, 2024',
  memberCount: '1,234',
  member_count: '1,234',
  count: '1,234',
  date: '2026-05-14',
  time: '12:00:00',
  latency: '42',
  bot_name: 'Bot',
  bot_tag: 'Bot#0000',
  bot_id: '444444444444444444',
  owner: 'Bot Owner',
  owner_id: '555555555555555555',
  command_count: '81',
  ping: '42ms',
  uptime: '12d 4h 18m',
  server_count: '128',
  user_count: '42,981',
  channel_count: '1,204',
  discordjs_version: '14.x',
  node_version: 'v20.x',
  memory: '148 MB',
  avatar_url: 'https://cdn.discordapp.com/embed/avatars/0.png',
  banner_url: 'https://cdn.discordapp.com/embed/avatars/1.png',
  invite_url: 'https://discord.com/oauth2/authorize',
  support_url: 'https://discord.gg/support',
  invite_link: '[Open Invite](https://discord.com/oauth2/authorize)',
  support_link: '[Support Server](https://discord.gg/support)',
  account_created: 'February 21, 2024',
  server_icon: 'https://cdn.discordapp.com/embed/avatars/2.png',
  activityName: 'ROBLOX',
  activityType: 'Playing',
  producerName: 'Producer',
  status: 'online',
  imageUrl: 'https://cdn.discordapp.com/embed/avatars/3.png',
  animatedAvatarUrl: 'https://cdn.discordapp.com/embed/avatars/4.png',
  animatedBannerUrl: 'https://cdn.discordapp.com/embed/avatars/5.png',
  profileUpdate: 'Activity updated',
  title: 'Song Title',
  author: 'Artist',
  duration: '3:21',
  posterUrl: 'https://cdn.discordapp.com/embed/avatars/0.png',
  expression: '2-5x0',
  result: '2',
  aliases: 'calc, math, solve',
  edition: 'Java',
  mc_name: 'akashsuu',
  mc_uuid: '0362e2fb-bd0a-4b49-8608-e0fc8af35cde',
  skin_link: '[Open Skin](https://minecraft.net)',
  skin_url: 'https://crafatar.com/skins/0362e2fbbd0a4b498608e0fc8af35cde',
  render_url: 'https://crafatar.com/renders/body/0362e2fbbd0a4b498608e0fc8af35cde',
  name_change_count: '2',
  name_history: 'akashsuu - First username',
  roblox_id: '156',
  roblox_name: 'builderman',
  display_name: 'builderman',
  description: 'Welcome to my profile.',
  verified: 'Yes',
  banned: 'No',
  friends: '142',
  following: '37',
  followers: '2,481',
  fortnite_name: 'Ninja',
  account_id: 'account_123',
  platform: 'PC',
  time_window: 'lifetime',
  wins: '3,412',
  kills: '125,884',
  matches: '28,430',
  kd: '4.42',
  win_rate: '12%',
  score: '9,840,221',
  profile_url: 'https://example.com/profile',
  profile_link: '[Open Profile](https://example.com/profile)',
  valorant_name: 'TenZ',
  valorant_tag: '0505',
  puuid: 'valorant-puuid',
  region: 'AP',
  account_level: '438',
  current_rank: 'Radiant',
  rr: '812',
  elo: '2,147',
  last_change: '+21',
  peak_rank: 'Radiant',
  leaderboard_rank: '#128',
  card_url: 'https://cdn.discordapp.com/embed/avatars/0.png',
  steam_id: '76561198000000000',
  steam_name: 'Akashsuu',
  visibility: 'Public',
  persona_state: 'Online',
  playtime: '284 hours',
  deaths: '83,102',
  mvps: '14,921',
  accuracy: '23.6%',
  headshots: '91,884',
  pubg_name: 'shroud',
  shard: 'steam',
  game_mode: 'squad-fpp',
  recent_matches: '14',
  rounds: '1,382',
  top10s: '602',
  damage: '1,024,391',
  longest_kill: '612.4m',
  uid: '618285856',
  input_name: 'Lumine',
  nickname: 'Lumine',
  level: '60',
  world_level: '8',
  signature: 'Ad astra abyssosque.',
  achievements: '1,102',
  abyss: '12-3',
  showcase_count: '8',
  namecard_id: '210001',
  profile_icon_id: '10000007',
  ttl: '300',
  phasmo_level: 'Level 84',
  prestige: 'Prestige 2',
  favorite_map: 'Sunny Meadows',
  favorite_ghost: 'Demon',
  difficulty: 'Professional',
  perfect_games: '18',
  country: 'IN',
  last_online: 'May 14, 2026',
  game_count: '142',
  total_playtime: '3,840 hours',
  recent_games: 'Counter-Strike 2, Phasmophobia, Terraria',
  epic_name: 'Akashsuu',
  linked_platforms: 'PC, PlayStation',
  privacy: 'Public',
  creator_code: 'AKASH',
  games: 'Fortnite, Rocket League',
  role: '@Member',
  roleMention: '@Member',
  roleId: '666666666666666666',
  deleted: '25',
  seconds: '10',
  lockedCount: '8',
  failedCount: '0',
  unlockedCount: '8',
  bannedCount: '2',
  targets: '@User1, @User2',
  ticketId: 'ticket-1024',
  ticket_id: 'ticket-1024',
  ticketUser: 'Akashsuu',
  ticket_user: 'Akashsuu',
  claimedBy: 'Staff',
  claimed_by: 'Staff',
  confirmationKeyword: 'confirm',
};

Object.assign(DEMO_VALUES, {
  userId: DEMO_VALUES.user_id,
  targetTag: DEMO_VALUES.target,
  botName: DEMO_VALUES.bot_name,
  botId: DEMO_VALUES.bot_id,
  ownerId: DEMO_VALUES.owner_id,
  ownerMention: '@Bot Owner',
  serverCount: DEMO_VALUES.server_count,
  userCount: DEMO_VALUES.user_count,
  botCount: '12',
  channelCount: DEMO_VALUES.channel_count,
  roleCount: '42',
  textChannels: '24',
  voiceChannels: '8',
  channels: '32',
  roles: '42',
  members: DEMO_VALUES.member_count,
  nodeVersion: DEMO_VALUES.node_version,
  discordVersion: DEMO_VALUES.discordjs_version,
  memoryUsed: '148 MB',
  memoryTotal: '512 MB',
  avatarUrl: DEMO_VALUES.avatar_url,
  bannerUrl: DEMO_VALUES.banner_url,
  inviteUrl: DEMO_VALUES.invite_url,
  iconUrl: DEMO_VALUES.avatar_url,
  authorName: DEMO_VALUES.user,
  image_url: DEMO_VALUES.imageUrl,
  thumbUrl: DEMO_VALUES.avatar_url,
  image: DEMO_VALUES.imageUrl,
  thumb: DEMO_VALUES.avatar_url,
  icon: DEMO_VALUES.avatar_url,
  logo: DEMO_VALUES.avatar_url,
  banner: DEMO_VALUES.banner_url,
  footer: 'Requested by Akashsuu',
  color: '#5865F2',
  url: DEMO_VALUES.profile_url,
  boostCount: '14',
  boostTier: '2',
  boostTierLabel: 'Level 2',
  boostLevel: 'Level 2',
  boosts: '14',
  boostBar: '######----',
  since: '5 minutes',
  days: '2',
  hours: '4',
  minutes: '18',
  years: '2',
  joinedAt: 'May 10, 2026',
  createdTimestamp: 'February 21, 2024',
  topRole: '@Member',
  isBot: 'No',
  statusText: 'Online',
  currentName: 'Old name',
  newName: 'New name',
  oldName: 'Old name',
  newPrefix: '?',
  oldPrefix: '!',
  emoji: ':sparkles:',
  answer: '42',
  question: 'What is the answer?',
  fact: 'Discord bots can be customized.',
  quote: 'Stay curious.',
  cat: 'https://cdn.discordapp.com/embed/avatars/0.png',
  gif: 'https://media.giphy.com/media/example/giphy.gif',
  gifUrl: 'https://media.giphy.com/media/example/giphy.gif',
  anime: 'Naruto',
  artist: DEMO_VALUES.author,
  poster: DEMO_VALUES.posterUrl,
  ticketNum: '1024',
  openedAt: 'May 14, 2026 12:00',
  closedAt: 'May 14, 2026 12:30',
  requester: DEMO_VALUES.mention,
  closerTag: 'Staff#0001',
  closeCommand: '!close',
  steamId: DEMO_VALUES.steam_id,
  gamertag: 'Akashsuu',
  abyssFloor: '12',
  abyssChamber: '3',
});

const VARIABLE_DESCRIPTIONS = {
  user: "Sender's username",
  tag: "Sender's Discord tag",
  id: "Sender's Discord user ID",
  mention: "Sender's mention",
  command: 'Command that triggered the node',
  args: 'Text typed after the command',
  reason: 'Action reason',
  server: 'Server name',
  channel: 'Channel name',
  memberCount: 'Server member count',
  date: 'Current date',
  time: 'Current time',
};

const VARIABLES = Object.entries(DEMO_VALUES).map(([name, demo]) => ({
  name,
  demo,
  desc: VARIABLE_DESCRIPTIONS[name] || 'Plugin template variable',
}));

function runtimeValues(message, extra = {}) {
  const now = new Date();
  const author = message?.author || {};
  const guild = message?.guild || {};
  const channel = message?.channel || {};
  const args = (message?.content || '').split(/\s+/).slice(1).join(' ');
  const authorMention = author.id ? `<@${author.id}>` : '';
  const channelMention = channel.id ? `<#${channel.id}>` : channel.name || '';

  return {
    ...DEMO_VALUES,
    user: author.username || DEMO_VALUES.user,
    username: author.username || DEMO_VALUES.username,
    tag: author.tag || DEMO_VALUES.tag,
    user_tag: author.tag || DEMO_VALUES.user_tag,
    id: author.id || DEMO_VALUES.id,
    user_id: author.id || DEMO_VALUES.user_id,
    mention: authorMention || DEMO_VALUES.mention,
    args,
    command: extra.command || DEMO_VALUES.command,
    server: guild.name || DEMO_VALUES.server,
    guild: guild.name || DEMO_VALUES.guild,
    serverId: guild.id || DEMO_VALUES.serverId,
    server_id: guild.id || DEMO_VALUES.server_id,
    guildId: guild.id || DEMO_VALUES.guildId,
    guild_id: guild.id || DEMO_VALUES.guild_id,
    channel: channel.name || DEMO_VALUES.channel,
    channelName: channel.name || DEMO_VALUES.channelName,
    channel_name: channel.name || DEMO_VALUES.channel_name,
    channelId: channel.id || DEMO_VALUES.channelId,
    channel_id: channel.id || DEMO_VALUES.channel_id,
    channelMention,
    channel_mention: channelMention,
    memberCount: String(guild.memberCount ?? DEMO_VALUES.memberCount),
    member_count: String(guild.memberCount ?? DEMO_VALUES.member_count),
    date: now.toISOString().slice(0, 10),
    time: now.toTimeString().slice(0, 8),
    ...extra,
  };
}

function substitute(text, message, extra = {}) {
  const values = runtimeValues(message, extra);
  return String(text || '').replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g, (match, key) => {
    const value = values[key];
    return value === undefined || value === null ? match : String(value);
  });
}

function buildTemplateLiteral(text) {
  const escaped = String(text || '')
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/\{user\}|\{username\}/g, '${message.author?.username || ""}')
    .replace(/\{tag\}|\{user_tag\}/g, '${message.author?.tag || ""}')
    .replace(/\{id\}|\{user_id\}/g, '${message.author?.id || ""}')
    .replace(/\{mention\}/g, '${`<@${message.author?.id}>`}')
    .replace(/\{args\}/g, '${message.content.split(" ").slice(1).join(" ")}')
    .replace(/\{command\}/g, '${cmd || ""}')
    .replace(/\{server\}|\{guild\}/g, '${message.guild?.name || "unknown"}')
    .replace(/\{serverId\}|\{server_id\}|\{guildId\}|\{guild_id\}/g, '${message.guild?.id || ""}')
    .replace(/\{channel\}|\{channelName\}|\{channel_name\}/g, '${message.channel?.name || "unknown"}')
    .replace(/\{channelId\}|\{channel_id\}/g, '${message.channel?.id || ""}')
    .replace(/\{channelMention\}|\{channel_mention\}/g, '${message.channel?.id ? `<#${message.channel.id}>` : ""}')
    .replace(/\{memberCount\}|\{member_count\}/g, '${message.guild?.memberCount ?? 0}')
    .replace(/\{target\}/g, '${_target?.user?.tag || "Unknown"}')
    .replace(/\{targetName\}|\{target_name\}/g, '${_target?.user?.username || "Unknown"}')
    .replace(/\{targetId\}|\{target_id\}/g, '${_target?.user?.id || "0"}')
    .replace(/\{targetMention\}|\{target_mention\}/g, '${`<@${_target?.user?.id}>`}')
    .replace(/\{reason\}/g, '${_reason || "No reason provided"}')
    .replace(/\{latency\}/g, '${_lat ?? 0}')
    .replace(/\{date\}/g, '${new Date().toISOString().slice(0,10)}')
    .replace(/\{time\}/g, '${new Date().toTimeString().slice(0,8)}');

  return '`' + escaped + '`';
}

module.exports = { VARIABLES, DEMO_VALUES, substitute, buildTemplateLiteral };
