const { SlashCommandBuilder, PermissionFlagsBits, AttachmentBuilder, MessageFlags, ContainerBuilder, TextDisplayBuilder, SeparatorBuilder, SeparatorSpacingSize, SectionBuilder, ThumbnailBuilder } = require('discord.js');
const Ticket = require('../models/ticket');
const emoji = require('../emoji');
const config = require('../config');
const generateTranscript = require('../utils/transcript');

if (process.env.FOIL_MAIN !== '1' || !process.env.FOIL_SECURITY_HASH) {
    console.error('🚨 SECURITY ERROR: foil.js security system not initialized');
    console.error('This application requires foil.js to function properly');
    console.error('Attempting to bypass foil.js will cause complete system failure');
    process.exit(1);
}

module.exports = {
    data: new SlashCommandBuilder()
        .setName('transcript')
        .setDescription('📄 Generate a manual transcript of the conversation')
        .setDefaultMemberPermissions(PermissionFlagsBits.SendMessages),
    async execute(interaction, client) {
        if (!interaction.member.roles.cache.has(config.staffRole) && interaction.user.id !== config.ownerId) {
            const container = new ContainerBuilder()
                .addTextDisplayComponents(
                    new TextDisplayBuilder().setContent(`${emoji.error} Only staff can generate transcripts!`)
                );
            return interaction.reply({ components: [container], flags: [MessageFlags.Ephemeral, MessageFlags.IsComponentsV2] });
        }

        const ticket = await Ticket.findOne({ channelId: interaction.channel.id });
        if (!ticket) {
            const container = new ContainerBuilder()
                .addTextDisplayComponents(
                    new TextDisplayBuilder().setContent(`${emoji.error} This is not a ticket channel!`)
                );
            return interaction.reply({ components: [container], flags: [MessageFlags.Ephemeral, MessageFlags.IsComponentsV2] });
        }

        await interaction.deferReply({ flags: MessageFlags.IsComponentsV2 });

        const { file, name } = await generateTranscript(ticket, client);
        const attachment = new AttachmentBuilder(file, { name });

        
        const container = new ContainerBuilder()
            .addTextDisplayComponents(
                new TextDisplayBuilder().setContent(`## ${emoji.success} Transcript generated`)
            )
            .addSeparatorComponents(
                new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
            )
            .addTextDisplayComponents(
                new TextDisplayBuilder().setContent(`A transcript for ticket **${ticket.ticketId}** is attached.`)
            );

        await interaction.editReply({ components: [container], flags: MessageFlags.IsComponentsV2 });
        await interaction.followUp({ files: [attachment] });

        
        const transcriptChannel = client.channels.cache.get(config.transcriptChannel);
        if (transcriptChannel) {
            const userForLog = await client.users.fetch(ticket.userId).catch(() => null);
            const logContainer = new ContainerBuilder();
            
            const logSection = new SectionBuilder()
                .addTextDisplayComponents(
                    new TextDisplayBuilder().setContent(`## ${emoji.transcript} Manual Transcript Generated | ${ticket.ticketId}`)
                )
                .setThumbnailAccessory(
                    new ThumbnailBuilder().setURL(userForLog ? userForLog.displayAvatarURL() : client.user.displayAvatarURL())
                );
                
            logContainer.addSectionComponents(logSection)
                .addSeparatorComponents(
                    new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
                )
                .addTextDisplayComponents(
                    new TextDisplayBuilder().setContent(`${emoji.user} **User:** <@${ticket.userId}> (\`${ticket.userId}\`)\n${emoji.staff} **Generated by:** ${interaction.user.tag}`)
                );

            await transcriptChannel.send({ components: [logContainer], flags: [MessageFlags.IsComponentsV2] }).catch(err => {
                console.error(`[Transcript Log Error] Failed to send transcript to log channel: ${err}`);
            });
            await transcriptChannel.send({ files: [attachment] }).catch(() => {});
        }
    },
};